// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['AddTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function GetCombinedFilteredTasks(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['GetCombinedFilteredTasks'](arg1, arg2, arg3, arg4);
}

export function GetFilteredTasks(arg1) {
  return window['go']['backend']['App']['GetFilteredTasks'](arg1);
}

export function GetSortedTasks(arg1, arg2) {
  return window['go']['backend']['App']['GetSortedTasks'](arg1, arg2);
}

export function GetTasks() {
  return window['go']['backend']['App']['GetTasks']();
}

export function GetTasksByDateFilter(arg1) {
  return window['go']['backend']['App']['GetTasksByDateFilter'](arg1);
}

export function ToggleTask(arg1) {
  return window['go']['backend']['App']['ToggleTask'](arg1);
}
