// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.Task>;

export function DeleteTask(arg1:number):Promise<boolean>;

export function GetCombinedFilteredTasks(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<backend.Task>>;

export function GetFilteredTasks(arg1:string):Promise<Array<backend.Task>>;

export function GetSortedTasks(arg1:string,arg2:boolean):Promise<Array<backend.Task>>;

export function GetTasks():Promise<Array<backend.Task>>;

export function GetTasksByDateFilter(arg1:string):Promise<Array<backend.Task>>;

export function ToggleTask(arg1:number):Promise<boolean>;
